remote_theme: peterdesmet/petridish@2.0

title: Jesper Bojeryd
description: This is testing out a new website

logo: /assets/compressed.jpg

email: jesperbojeryd@ucla.edu
twitter_username: bojerydjesper
github_username: bojeryd91

colors:
  links: "#007bff"                      # Color for links: use a readable color that contrasts well with dark text
  banner: "#007bff"                     # Background color for page banners: use color that contrasts well with white
  footer: "#6c757d"                     # Background color for footer: use color that contrasts well with white
font_serif: true                        # Font type for page content: serif (default) or slightly smaller sans-serif
rounded_corners: true                   # Enable (default) rounded corners on boxes and buttons
