remote_theme: peterdesmet/petridish@2.0

title: Jesper Böjeryd
description: This is testing out a new website

logo: /assets/compressed.jpg

email: jesperbojeryd@ucla.edu
twitter_username: bojerydjesper
github_username: bojeryd91
#linkedin_username: jesperbojeryd

#font:         "'Noto Sans', Helvetica, Arial, sans-serif"   # A test
#font_heading: "'Roboto Slab', Helvetica, Arial, sans-serif" # A test

font:         "'Noto Sans', Helvetica, Arial, sans-serif"   # A test
font_heading: "'Roboto Slab', Helvetica, Arial, sans-serif" # A test

colors:
   links: "#CB3244"                     # Color for links: use a readable color that contrasts well with dark text
  banner: "#CB3244"                     # Background color for page banners: use color that contrasts well with white
  footer: "#CB3244"                     # Background color for footer: use color that contrasts well with white
font_serif: true                        # Font type for page content: serif (default) or slightly smaller sans-serif
rounded_corners: true                   # Enable (default) rounded corners on boxes and buttons
